// =============================================================================
// ファイル名: BrandData.swift
// 役割: ブランド一覧と読み仮名データ。ふりがな検索対応。
// =============================================================================

import Foundation

struct BrandEntry: Identifiable, Codable {
    var id: String = UUID().uuidString
    let name: String       // 画面上の表示名
    let reading: String    // カタカナ読み（ふりがな検索用）
    var order: Int = 0     // 表示順（Firestore管理用）
}

// 検索用文字列正規化：ひらがな→カタカナ、大文字→小文字、記号除去
func normalizeForSearch(_ text: String) -> String {
    let mutable = NSMutableString(string: text) as CFMutableString
    CFStringTransform(mutable, nil, kCFStringTransformHiraganaKatakana, false)
    return (mutable as String)
        .lowercased()
        .replacingOccurrences(of: " ", with: "")
        .replacingOccurrences(of: "　", with: "")
        .replacingOccurrences(of: "&", with: "and")
}

/// ブランド名で検索（表示名または読み仮名にマッチ）
func filterBrands(_ brands: [BrandEntry], query: String) -> [BrandEntry] {
    if query.isEmpty { return brands }
    let normalizedQuery = normalizeForSearch(query)
    return brands.filter {
        normalizeForSearch($0.name).contains(normalizedQuery) ||
        $0.reading.contains(normalizedQuery)
    }
}

/// すべてのブランドデータ（読み仮名付き）
/// 子供服・ベビー服・スタイ・帽子・靴・靴下など、子供関連ブランドを網羅
let allBrands: [BrandEntry] = [
    // === ファストファッション・大手カジュアル ===
    BrandEntry(name: "UNIQLO", reading: "ユニクロ"),
    BrandEntry(name: "無印良品", reading: "ムジルシリョウヒン"),
    BrandEntry(name: "GU", reading: "ジーユー"),
    BrandEntry(name: "H&M", reading: "エイチアンドエム"),
    BrandEntry(name: "Zara", reading: "ザラ"),
    BrandEntry(name: "GAP", reading: "ギャップ"),
    BrandEntry(name: "babyGAP", reading: "ベビーギャップ"),
    BrandEntry(name: "Old Navy", reading: "オールドネイビー"),
    BrandEntry(name: "ZARA KIDS", reading: "ザラキッズ"),
    BrandEntry(name: "H&M Kids", reading: "エイチアンドエムキッズ"),
    BrandEntry(name: "global work", reading: "グローバルワーク"),
    BrandEntry(name: "LOWRYS FARM", reading: "ローリーズファーム"),
    BrandEntry(name: "niko and...", reading: "ニコアンド"),
    BrandEntry(name: "studio CLIP", reading: "スタディオクリップ"),
    BrandEntry(name: "Samansa Mos2", reading: "サマンサモスモス"),
    BrandEntry(name: "SM2", reading: "サマンサモスモス"),
    BrandEntry(name: "earth music&ecology", reading: "アースミュージックアンドエコロジー"),
    BrandEntry(name: "earth music&ecology Kids", reading: "アースミュージックアンドエコロジーキッズ"),

    // === 日系キッズブランド（人気・定番） ===
    BrandEntry(name: "mikihouse", reading: "ミキハウス"),
    BrandEntry(name: "DOUBLE_B", reading: "ダブルビー"),
    BrandEntry(name: "HOT BISCUITS", reading: "ホットビスケッツ"),
    BrandEntry(name: "familiar", reading: "ファミリア"),
    BrandEntry(name: "西松屋", reading: "ニシマツヤ"),
    BrandEntry(name: "しまむら", reading: "シマムラ"),
    BrandEntry(name: "COMME CA ISM", reading: "コムサイスム"),
    BrandEntry(name: "COMME CA DU MODE", reading: "コムサデュモード"),
    BrandEntry(name: "F.O.KIDS", reading: "エフオーキッズ"),
    BrandEntry(name: "F.O.International", reading: "エフオーインターナショナル"),
    BrandEntry(name: "BREEZE", reading: "ブリーズ"),
    BrandEntry(name: "BREEZE BRONCO", reading: "ブリーズブロンコ"),
    BrandEntry(name: "BONJOUR DIARY", reading: "ボンジュールダイアリー"),
    BrandEntry(name: "Ribbon Tribe", reading: "リボントライブ"),
    BrandEntry(name: "ALGY", reading: "アルジー"),
    BrandEntry(name: "セラフ", reading: "セラフ"),
    BrandEntry(name: "ナルミヤ", reading: "ナルミヤ"),
    BrandEntry(name: "petit jam", reading: "プチジャム"),
    BrandEntry(name: "Souris", reading: "スーリー"),
    BrandEntry(name: "mou jon jon", reading: "ムージョンジョン"),
    BrandEntry(name: "LOVEtoxic", reading: "ラブトキシック"),
    BrandEntry(name: "Rodiex Spot", reading: "ロディースポット"),
    BrandEntry(name: "JENNI", reading: "ジェニィ"),
    BrandEntry(name: "PINK-latte", reading: "ピンクラテ"),
    BrandEntry(name: "repipi armario", reading: "レピピアルマリオ"),
    BrandEntry(name: "X-girl Stages", reading: "エックスガールステージズ"),
    BrandEntry(name: "b・ROOM", reading: "ビールーム"),
    BrandEntry(name: "チャンピオン", reading: "チャンピオン"),
    BrandEntry(name: "Champion Kids", reading: "チャンピオンキッズ"),
    BrandEntry(name: "BRANSHES", reading: "ブランシェス"),
    BrandEntry(name: "apres les cours", reading: "アプレレクール"),
    BrandEntry(name: "MARKEY'S", reading: "マーキーズ"),
    BrandEntry(name: "MPS", reading: "エムピーエス"),
    BrandEntry(name: "devirock", reading: "デビロック"),
    BrandEntry(name: "BACK ALLEY", reading: "バックアレイ"),
    BrandEntry(name: "CIAOPANIC TYPY", reading: "チャオパニックティピー"),
    BrandEntry(name: "Jeans-b", reading: "ジーンズベー"),
    BrandEntry(name: "Skipland", reading: "スキップランド"),
    BrandEntry(name: "ニッセン", reading: "ニッセン"),
    BrandEntry(name: "ベルメゾン", reading: "ベルメゾン"),
    BrandEntry(name: "千趣会", reading: "センシュカイ"),
    BrandEntry(name: "赤ちゃん本舗", reading: "アカチャンホンポ"),
    BrandEntry(name: "トイザらス", reading: "トイザラス"),
    BrandEntry(name: "ベビーザらス", reading: "ベビーザラス"),
    BrandEntry(name: "Motherways", reading: "マザウェイズ"),
    BrandEntry(name: "HONEYS", reading: "ハニーズ"),
    BrandEntry(name: "INGNI", reading: "イング"),

    // === セレクトショップ・百貨店 ===
    BrandEntry(name: "SHIPS", reading: "シップス"),
    BrandEntry(name: "SHIPS Kids", reading: "シップスキッズ"),
    BrandEntry(name: "SHIPS any", reading: "シップスエニー"),
    BrandEntry(name: "BEAMS", reading: "ビームス"),
    BrandEntry(name: "BEAMS MINI", reading: "ビームスミニ"),
    BrandEntry(name: "BEAMS KIDS", reading: "ビームスキッズ"),
    BrandEntry(name: "UNITED ARROWS", reading: "ユナイテッドアローズ"),
    BrandEntry(name: "green label relaxing", reading: "グリーンレーベルリラクシング"),
    BrandEntry(name: "JOURNAL STANDARD", reading: "ジャーナルスタンダード"),
    BrandEntry(name: "EDIFICE", reading: "エディフィス"),
    BrandEntry(name: "EDIFICE Kids", reading: "エディフィスキッズ"),
    BrandEntry(name: "BEAUTY&YOUTH", reading: "ビューティアンドユース"),
    BrandEntry(name: "TOMORROWLAND", reading: "トゥモローランド"),
    BrandEntry(name: "STUDIOUS", reading: "ステュディオス"),
    BrandEntry(name: "ESTNATION", reading: "エストネーション"),
    BrandEntry(name: "Barneys New York", reading: "バーニーズニューヨーク"),
    BrandEntry(name: "伊勢丹", reading: "イセタン"),
    BrandEntry(name: "三越", reading: "ミツコシ"),
    BrandEntry(name: "高島屋", reading: "タカシマヤ"),
    BrandEntry(name: "そごう", reading: "ソゴウ"),
    BrandEntry(name: "西武", reading: "セイブ"),
    BrandEntry(name: "東武", reading: "トウブ"),
    BrandEntry(name: "東急", reading: "トウキュウ"),
    BrandEntry(name: "小田急", reading: "オダキュウ"),
    BrandEntry(name: "京王", reading: "ケイオウ"),
    BrandEntry(name: "阪急", reading: "ハンキュウ"),
    BrandEntry(name: "大丸", reading: "ダイマル"),
    BrandEntry(name: "松坂屋", reading: "マツザカヤ"),
    BrandEntry(name: "PARCO", reading: "パルコ"),
    BrandEntry(name: "LUMINE", reading: "ルミネ"),
    BrandEntry(name: "マルイ", reading: "マルイ"),
    BrandEntry(name: "イトーヨーカドー", reading: "イトーヨーカドー"),
    BrandEntry(name: "イオン", reading: "イオン"),
    BrandEntry(name: "LOPIA", reading: "ロピア"),
    BrandEntry(name: "ロペピクニック", reading: "ロペピクニック"),
    BrandEntry(name: "URBAN RESEARCH", reading: "アーバンリサーチ"),
    BrandEntry(name: "DOORS", reading: "ドアーズ"),

    // === インターナショナルキッズ ===
    BrandEntry(name: "Carter's", reading: "カーターズ"),
    BrandEntry(name: "Petit Bateau", reading: "プチバトー"),
    BrandEntry(name: "Boden", reading: "ボーデン"),
    BrandEntry(name: "Gymboree", reading: "ジンボリー"),
    BrandEntry(name: "The Children's Place", reading: "ザチルドレンズプレイス"),
    BrandEntry(name: "next", reading: "ネクスト"),
    BrandEntry(name: "Mothercare", reading: "マザーケア"),
    BrandEntry(name: "Frugi", reading: "フルージ"),
    BrandEntry(name: "Boboli", reading: "ボボリ"),
    BrandEntry(name: "Mexx", reading: "メックス"),
    BrandEntry(name: "Oilily", reading: "オイリリー"),
    BrandEntry(name: "Jacadi", reading: "ジャカディ"),
    BrandEntry(name: "Bonpoint", reading: "ボンポワン"),
    BrandEntry(name: "BURBERRY Children", reading: "バーバリーチルドレン"),
    BrandEntry(name: "BURBERRY", reading: "バーバリー"),
    BrandEntry(name: "GUCCI Kids", reading: "グッチキッズ"),
    BrandEntry(name: "ARMANI Junior", reading: "アルマーニジュニア"),
    BrandEntry(name: "DIESEL Kid", reading: "ディーゼルキッド"),
    BrandEntry(name: "D&G Junior", reading: "ドルチェアンドガッバーナジュニア"),
    BrandEntry(name: "Dolce&Gabbana", reading: "ドルチェアンドガッバーナ"),
    BrandEntry(name: "VERSACE Young", reading: "ヴェルサーチヤング"),
    BrandEntry(name: "FENDI Kids", reading: "フェンディキッズ"),
    BrandEntry(name: "Chloe Kids", reading: "クロエキッズ"),
    BrandEntry(name: "KENZO Kids", reading: "ケンゾーキッズ"),
    BrandEntry(name: "Paul Smith Junior", reading: "ポールスミスジュニア"),
    BrandEntry(name: "MOSCHINO Baby", reading: "モスキーノベビー"),
    BrandEntry(name: "MARC JACOBS Kids", reading: "マークジェイコブスキッズ"),
    BrandEntry(name: "STELLA McCARTNEY Kids", reading: "ステラマッカートニーキッズ"),
    BrandEntry(name: "Little Marc Jacobs", reading: "リトルマークジェイコブス"),

    // === スポーツ・カジュアルブランド ===
    BrandEntry(name: "POLO Ralph Lauren", reading: "ポロラルフローレン"),
    BrandEntry(name: "POLO Ralph Lauren Kids", reading: "ポロラルフローレンキッズ"),
    BrandEntry(name: "Tommy Hilfiger", reading: "トミーヒルフィガー"),
    BrandEntry(name: "Tommy Hilfiger Kids", reading: "トミーヒルフィガーキッズ"),
    BrandEntry(name: "Calvin Klein", reading: "カルバンクライン"),
    BrandEntry(name: "LACOSTE", reading: "ラコステ"),
    BrandEntry(name: "Fred Perry", reading: "フレッドペリー"),
    BrandEntry(name: "Benetton", reading: "ベネトン"),
    BrandEntry(name: "United Colors of Benetton", reading: "ユナイテッドカラーズオブベネトン"),
    BrandEntry(name: "Nike", reading: "ナイキ"),
    BrandEntry(name: "Nike Kids", reading: "ナイキキッズ"),
    BrandEntry(name: "adidas", reading: "アディダス"),
    BrandEntry(name: "adidas Kids", reading: "アディダスキッズ"),
    BrandEntry(name: "PUMA", reading: "プーマ"),
    BrandEntry(name: "PUMA Kids", reading: "プーマキッズ"),
    BrandEntry(name: "Under Armour", reading: "アンダーアーマー"),
    BrandEntry(name: "DESCENTE", reading: "デサント"),
    BrandEntry(name: "ASICS", reading: "アシックス"),
    BrandEntry(name: "MIZUNO", reading: "ミズノ"),
    BrandEntry(name: "New Balance", reading: "ニューバランス"),
    BrandEntry(name: "New Balance Kids", reading: "ニューバランスキッズ"),
    BrandEntry(name: "CONVERSE", reading: "コンバース"),
    BrandEntry(name: "CONVERSE KIDS", reading: "コンバースキッズ"),
    BrandEntry(name: "VANS", reading: "ヴァンズ"),
    BrandEntry(name: "VANS Kids", reading: "ヴァンズキッズ"),
    BrandEntry(name: "Reebok", reading: "リーボック"),
    BrandEntry(name: "Reebok Kids", reading: "リーボックキッズ"),
    BrandEntry(name: "Lee", reading: "リー"),
    BrandEntry(name: "Lee Kids", reading: "リーキッズ"),
    BrandEntry(name: "Wrangler", reading: "ラングラー"),
    BrandEntry(name: "Levi's", reading: "リーバイス"),
    BrandEntry(name: "Dickies", reading: "ディッキーズ"),
    BrandEntry(name: "RUSTY", reading: "ラスティ"),
    BrandEntry(name: "O'NEILL", reading: "オニール"),
    BrandEntry(name: "Quiksilver", reading: "クイックシルバー"),
    BrandEntry(name: "ROXY", reading: "ロキシー"),
    BrandEntry(name: "Billabong", reading: "ビラボン"),
    BrandEntry(name: "Hurley", reading: "ハーレー"),
    BrandEntry(name: "ELEMENT", reading: "エレメント"),
    BrandEntry(name: "STUSSY", reading: "ステューシー"),
    BrandEntry(name: "Supreme", reading: "シュプリーム"),
    BrandEntry(name: "A BATHING APE", reading: "アベイシングエイプ"),
    BrandEntry(name: "BAPE KIDS", reading: "ベイプキッズ"),

    // === シューズ・靴 ===
    BrandEntry(name: "MOONSTAR", reading: "ムーンスター"),
    BrandEntry(name: "ASAHI", reading: "アサヒ"),
    BrandEntry(name: "IFME", reading: "イフミー"),
    BrandEntry(name: "CROCS", reading: "クロックス"),
    BrandEntry(name: "KEEN", reading: "キーン"),
    BrandEntry(name: "KEEN Kids", reading: "キーンキッズ"),
    BrandEntry(name: "Teva", reading: "テバ"),
    BrandEntry(name: "Teva Kids", reading: "テバキッズ"),
    BrandEntry(name: "MERRELL", reading: "メレル"),
    BrandEntry(name: "MERRELL Kids", reading: "メレルキッズ"),
    BrandEntry(name: "Timberland", reading: "ティンバーランド"),
    BrandEntry(name: "Dr.Martens", reading: "ドクターマーチン"),
    BrandEntry(name: "UGG", reading: "アグ"),
    BrandEntry(name: "UGG Kids", reading: "アグキッズ"),
    BrandEntry(name: "BIRKENSTOCK", reading: "ビルケンシュトック"),
    BrandEntry(name: "Superstar", reading: "スーパースター"),
    BrandEntry(name: "Columbia", reading: "コロンビア"),
    BrandEntry(name: "Columbia Kids", reading: "コロンビアキッズ"),
    BrandEntry(name: "THE NORTH FACE", reading: "ザノースフェイス"),
    BrandEntry(name: "THE NORTH FACE Kids", reading: "ザノースフェイスキッズ"),
    BrandEntry(name: "Patagonia", reading: "パタゴニア"),
    BrandEntry(name: "Patagonia Kids", reading: "パタゴニアキッズ"),
    BrandEntry(name: "Montbell", reading: "モンベル"),
    BrandEntry(name: "Snow Peak", reading: "スノーピーク"),
    BrandEntry(name: "NEW ERA", reading: "ニューエラ"),
    BrandEntry(name: "NEW ERA KIDS", reading: "ニューエラキッズ"),

    // === スタイ・よだれかけ ===
    BrandEntry(name: "MARLMARL", reading: "マールマール"),
    BrandEntry(name: "10mois", reading: "ディモア"),
    BrandEntry(name: "e-bib", reading: "エビブ"),
    BrandEntry(name: "Aden+Anais", reading: "エイデンアンドアネイ"),
    BrandEntry(name: "BIBS", reading: "ビブス"),
    BrandEntry(name: "SKIP HOP", reading: "スキップホップ"),
    BrandEntry(name: "Lassig", reading: "ラシグ"),
    BrandEntry(name: "Mushie", reading: "ムシー"),
    BrandEntry(name: "KONGES SLOD", reading: "コングススロイド"),
    BrandEntry(name: "LIEWOOD", reading: "リーウッド"),
    BrandEntry(name: "noa noa miniature", reading: "ノアノアミニチュア"),
    BrandEntry(name: "MINI RODINI", reading: "ミニロディーニ"),
    BrandEntry(name: "tinycottons", reading: "タイニーコットンズ"),
    BrandEntry(name: "bobo choses", reading: "ボボショーズ"),
    BrandEntry(name: "HUXBABY", reading: "ハックスベイビー"),
    BrandEntry(name: "Main Sauvage", reading: "マンソヴァージュ"),
    BrandEntry(name: "Meroware", reading: "メロウェア"),
    BrandEntry(name: "BABYBJORN", reading: "ベビービョルン"),
    BrandEntry(name: "Ergobaby", reading: "エルゴベビー"),
    BrandEntry(name: "Stokke", reading: "ストッケ"),
    BrandEntry(name: "Bugaboo", reading: "バガブー"),
    BrandEntry(name: "Aprica", reading: "アップリカ"),
    BrandEntry(name: "Combi", reading: "コンビ"),
    BrandEntry(name: "Chicco", reading: "キッコ"),
    BrandEntry(name: "Graco", reading: "グレコ"),

    // === 帽子 ===
    BrandEntry(name: "KANGOL", reading: "カンゴール"),
    BrandEntry(name: "PRINCE", reading: "プリンス"),
    BrandEntry(name: "OVERRIDE", reading: "オーバーライド"),
    BrandEntry(name: "CA4LA", reading: "カシラ"),
    BrandEntry(name: "NEW YORK HAT", reading: "ニューヨークハット"),
    BrandEntry(name: "田中帽子店", reading: "タナカボウシテン"),
    BrandEntry(name: "chocola", reading: "ショコラ"),

    // === 靴下・タイツ・インナー ===
    BrandEntry(name: "Tabio", reading: "タビオ"),
    BrandEntry(name: "靴下屋", reading: "クツシタヤ"),
    BrandEntry(name: "FALKE", reading: "ファルケ"),
    BrandEntry(name: "福助", reading: "フクスケ"),
    BrandEntry(name: "NAIGAI", reading: "ナイガイ"),
    BrandEntry(name: "Okamoto", reading: "オカモト"),
    BrandEntry(name: "Wacoal", reading: "ワコール"),
    BrandEntry(name: "Triumph", reading: "トリンプ"),
    BrandEntry(name: "PEACH JOHN", reading: "ピーチジョン"),
    BrandEntry(name: "une nana cool", reading: "ウンナナクール"),
    BrandEntry(name: "GUNZE", reading: "グンゼ"),
    BrandEntry(name: "ATSUGI", reading: "アツギ"),

    // === ベビー用品・マタニティ ===
    BrandEntry(name: "Pampers", reading: "パンパース"),
    BrandEntry(name: "Merries", reading: "メリーズ"),
    BrandEntry(name: "Moony", reading: "ムーニー"),
    BrandEntry(name: "GOO.N", reading: "グーン"),
    BrandEntry(name: "Genki!", reading: "ゲンキ"),
    BrandEntry(name: "自然の恵み", reading: "シゼンノメグミ"),
    BrandEntry(name: "mama&kids", reading: "ママアンドキッズ"),
    BrandEntry(name: "Aveeno Baby", reading: "アビーノベビー"),
    BrandEntry(name: "Johnson's", reading: "ジョンソンズ"),
    BrandEntry(name: "WAKODO", reading: "ワコドウ"),
    BrandEntry(name: "Pigeon", reading: "ピジョン"),
    BrandEntry(name: "Dr.Betta", reading: "ドクターベッタ"),
    BrandEntry(name: "Betta", reading: "ベッタ"),

    // === 北欧・インポート ===
    BrandEntry(name: "Jellycat", reading: "ジェリーキャット"),
    BrandEntry(name: "Done by Deer", reading: "ダンバイディア"),
    BrandEntry(name: "Sebra", reading: "セブラ"),
    BrandEntry(name: "Ferm Living", reading: "ファームリビング"),
    BrandEntry(name: "OYOY", reading: "オイオイ"),
    BrandEntry(name: "OYOY LIVING", reading: "オイオイリビング"),
    BrandEntry(name: "garbo&friends", reading: "ガルボアンドフレンズ"),
    BrandEntry(name: "Elodie Details", reading: "エロディーディテールズ"),
    BrandEntry(name: "Milestone", reading: "マイルストーン"),
    BrandEntry(name: "Natruba", reading: "ナトルバ"),
    BrandEntry(name: "Hevea", reading: "ヘヴィア"),
    BrandEntry(name: "Cam Cam", reading: "カムカム"),
    BrandEntry(name: "That's mine", reading: "ザッツマイン"),

    // === デニム・カジュアル ===
    BrandEntry(name: "DENIM DUNGAREE", reading: "デニムダンガリー"),
    BrandEntry(name: "GO TO HOLLYWOOD", reading: "ゴートゥーハリウッド"),
    BrandEntry(name: "NUMBER(N)INE", reading: "ナンバーナイン"),
    BrandEntry(name: "NEARLY", reading: "ニアリー"),
    BrandEntry(name: "GRAND GROUND", reading: "グランドグラウンド"),
    BrandEntry(name: "JUNK STORE", reading: "ジャンクストア"),
    BrandEntry(name: "SMOOTHY", reading: "スムージー"),
    BrandEntry(name: "GROOVY COLORS", reading: "グルービーカラーズ"),
    BrandEntry(name: "JIPPON", reading: "ジポン"),
    BrandEntry(name: "RAG MART", reading: "ラグマート"),
    BrandEntry(name: "Ocean&Ground", reading: "オーシャンアンドグラウンド"),
    BrandEntry(name: "Ampersand", reading: "アンパサンド"),
    BrandEntry(name: "Beau Loves", reading: "ボーラブズ"),
    BrandEntry(name: "Wolf&Rita", reading: "ウルフアンドリタ"),
    BrandEntry(name: "Tinycottons", reading: "タイニーコットンズ"),
    BrandEntry(name: "The Campamento", reading: "ザカンパメント"),
    BrandEntry(name: "Repose AMS", reading: "レポーズエーエムエス"),
    BrandEntry(name: "Maed for mini", reading: "メードフォーミニ"),
    BrandEntry(name: "Molo", reading: "モロ"),
    BrandEntry(name: "Soft Gallery", reading: "ソフトギャラリー"),

    // === 和服・フォーマル ===
    BrandEntry(name: "一越", reading: "ヒトコシ"),
    BrandEntry(name: "七五三", reading: "シチゴサン"),
    BrandEntry(name: "京屋", reading: "キョウヤ"),
    BrandEntry(name: "はかま", reading: "ハカマ"),
    BrandEntry(name: "着物", reading: "キモノ"),
    BrandEntry(name: "七五三着物", reading: "シチゴサンキモノ"),
    BrandEntry(name: "お宮参り", reading: "オミヤマイリ"),
    BrandEntry(name: "初節句", reading: "ハツセック"),
    BrandEntry(name: "お食い初め", reading: "オクイゾメ"),

    // === 水着 ===
    BrandEntry(name: "OshKosh", reading: "オシュコシュ"),
    BrandEntry(name: "OshKosh B'gosh", reading: "オシュコシュビゴッシュ"),
    BrandEntry(name: "RUSTY", reading: "ラスティ"),
    BrandEntry(name: "ROXY", reading: "ロキシー"),
    BrandEntry(name: "Speedo", reading: "スピード"),
    BrandEntry(name: "arena", reading: "アリーナ"),
    BrandEntry(name: "MIZUNO", reading: "ミズノ"),
    BrandEntry(name: "ASICS", reading: "アシックス"),
    BrandEntry(name: "NIKE", reading: "ナイキ"),
    BrandEntry(name: "adidas", reading: "アディダス"),
]

